flowchart LR

    csv[(CSV Files)]
    npz[(NPZ Files)]
    sqlite[(SQLite Files)]
    
    subgraph parsl["Parsl Workflows"]
        subgraph spacer [" "]
            subgraph data_grammar ["Data Grammar\n"]
                subgraph spacer2 [" "]
                    subgraph sql["DuckDB SQL"]
                        arrow["Arrow Table(s)"]
                    end
                    parquet[("Parquet File(s)")]
                end
            end
        end
    end

    csv --> sql
    sqlite --> sql
    npz --> sql

    arrow --> parquet


style sql fill:#6EE7B7,stroke:#999999;
style parsl fill:#ffffff,stroke:#444444;
style spacer fill:#ffffff,stroke:#ffffff;
style spacer2 fill:#FFFFE1,stroke:#FFFFE1;
