# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        exclude: >
              (?x)^(
                  .*\.lock|.*\.csv
              )$
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
      - id: vulture
        args: ["dbmi-lunch-and-learn-arrow/presentation","dbmi-lunch-and-learn-arrow/dagger"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        # note: we install additional dependencies for
        # pylint due to it's dynamic analysis capabilities
        # and the way pre-commit references virtual environments.
        additional_dependencies:
          - "anyio"
          - "dagger-io"
